# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 The Scadek OS Project contributors

name=ScadekOS
init=/init
console_runner=/runner
hello=/bin/hello
grant_demo=/grant-test
ring_demo=/ring-test
prompt=/prompt
boot_script=/etc/scadek.rc
version_file=/etc/scadekos.version
kernel_version_file=/etc/scdk.version
console=interactive
milestone=kernel-os-parallel
