# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 The Scadek OS Project contributors

boot.mode=scadekos-devpreview.1
console=framebuffer
serial=optional
init=/init
grant_demo=/grant-test
ring_demo=/ring-test
